services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    volumes:
      - mongo:/data
  mongo-express:
    image: 'mongo-express:latest'
    container_name: 'mongo-express'
    restart: always
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=secret'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
volumes:
  mongo: {}