spring:
  data:
      mongodb:
        username: admin
        password: Nx1LS7D15svDqkfX
        host: maincluster.hseyvba.mongodb.net
        port: 27017
        database: ember-db
        authentication-database: admin

server:
  port: 8088
